apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  labels:
    env: demo
    type: frontend
spec:
  containers:
  - name: my-first-pod-containers
    image: nginx:latest
    ports:
    - containerPort: 80